
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUALS KEY NEWLINE VALUE\n    config : config key_value\n           | key_value\n    key_value : KEY EQUALS VALUE NEWLINE'
    
_lr_action_items = {'KEY':([0,1,2,4,7,],[3,3,-2,-1,-3,]),'$end':([1,2,4,7,],[0,-2,-1,-3,]),'EQUALS':([3,],[5,]),'VALUE':([5,],[6,]),'NEWLINE':([6,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'config':([0,],[1,]),'key_value':([0,1,],[2,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> config","S'",1,None,None,None),
  ('config -> config key_value','config',2,'p_config','npc.py',39),
  ('config -> key_value','config',1,'p_config','npc.py',40),
  ('key_value -> KEY EQUALS VALUE NEWLINE','key_value',4,'p_key_value','npc.py',48),
]
